SRC_FILES := $(wildcard *.c) \
             $(wildcard codec/*.c) \
             $(wildcard cru/*.c) \
			 $(wildcard crypto/*.c) \
			 $(wildcard display/*.c) \
			 $(wildcard gmac/*.c) \
			 $(wildcard pinctrl/*.c) \
			 $(wildcard pm/*.c)

include $(KERNEL_ROOT)/compiler.mk